version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: verita_ai
      POSTGRES_USER: verita
      POSTGRES_PASSWORD: verita_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://verita:verita_password@postgres:5432/verita_ai
      SYNC_DATABASE_URL: postgresql://verita:verita_password@postgres:5432/verita_ai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://verita:verita_password@postgres:5432/verita_ai
      SYNC_DATABASE_URL: postgresql://verita:verita_password@postgres:5432/verita_ai
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
    command: celery -A app.tasks worker --loglevel=info

volumes:
  postgres_data:
  redis_data: